Parent commit

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,71 +15,71 @@
 # limitations under the License.
 #
 
-name: build
+# name: build
 
-on:
-  pull_request:
-    branches:
-      - master
-  workflow_call:
+# on:
+#   pull_request:
+#     branches:
+#       - master
+#   workflow_call:
 
-jobs:
-  compile:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ ubuntu-latest, windows-latest ]
-        java: [ '8' ]
-    steps:
-      - uses: actions/checkout@v3
+# jobs:
+#   compile:
+#     runs-on: ${{ matrix.os }}
+#     strategy:
+#       matrix:
+#         os: [ ubuntu-latest, windows-latest ]
+#         java: [ '8' ]
+#     steps:
+#       - uses: actions/checkout@v3
 
-      - name: Set up JDK ${{ matrix.java }}
-        uses: actions/setup-java@v3
-        with:
-          distribution: temurin
-          java-version: ${{ matrix.java }}
+#       - name: Set up JDK ${{ matrix.java }}
+#         uses: actions/setup-java@v3
+#         with:
+#           distribution: temurin
+#           java-version: ${{ matrix.java }}
 
-      - uses: actions/cache@v3
-        with:
-          path: ~/.m2/repository
-          key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ matrix.os }}-maven-
+#       - uses: actions/cache@v3
+#         with:
+#           path: ~/.m2/repository
+#           key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
+#           restore-keys: |
+#             ${{ matrix.os }}-maven-
 
-      - name: Build with maven
-        run: mvn -B --errors --activate-profiles ci --no-transfer-progress package -DskipTests
+#       - name: Build with maven
+#         run: mvn -B --errors --activate-profiles ci --no-transfer-progress package -DskipTests
 
-  test:
-    needs: compile
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ ubuntu-latest, windows-latest ]
-        java: [ '8', '11', '17' ]
-    steps:
-      - uses: actions/checkout@v3
+#   test:
+#     needs: compile
+#     runs-on: ${{ matrix.os }}
+#     strategy:
+#       matrix:
+#         os: [ ubuntu-latest, windows-latest ]
+#         java: [ '8', '11', '17' ]
+#     steps:
+#       - uses: actions/checkout@v3
 
-      - name: Set up JDK ${{ matrix.java }}
-        uses: actions/setup-java@v3
-        with:
-          distribution: temurin
-          java-version: ${{ matrix.java }}
+#       - name: Set up JDK ${{ matrix.java }}
+#         uses: actions/setup-java@v3
+#         with:
+#           distribution: temurin
+#           java-version: ${{ matrix.java }}
 
-      - uses: actions/cache@v3
-        with:
-          path: ~/.m2/repository
-          key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ matrix.os }}-maven-
+#       - uses: actions/cache@v3
+#         with:
+#           path: ~/.m2/repository
+#           key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
+#           restore-keys: |
+#             ${{ matrix.os }}-maven-
 
-      - name: Build and test with maven
-        # Skip all static checks, they were already done in the compile jobs
-        run: mvn -B --errors --activate-profiles ci --no-transfer-progress package
+#       - name: Build and test with maven
+#         # Skip all static checks, they were already done in the compile jobs
+#         run: mvn -B --errors --activate-profiles ci --no-transfer-progress package
 
-      - name: Archive test results and logs
-        # if: success() || failure() to also get the test results on successful runs.
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: test-results-${{ matrix.java }}-${{ matrix.os }}
-          path: sshd-*/target/surefire-*
+#       - name: Archive test results and logs
+#         # if: success() || failure() to also get the test results on successful runs.
+#         if: failure()
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: test-results-${{ matrix.java }}-${{ matrix.os }}
+#           path: sshd-*/target/surefire-*
